#H2
spring:
   jpa:
      generate-ddl: true
      database: H2
      show-sql: true
      hibernate:
         ddl-auto: update
         use-new-id-generator-mappings: true
   datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:~/restaurant
      username: sa
      password:
#   h2:
#     console:
#       enabled: true
#       path: /h2
server:
   port: 8080
   contextPath: /restaurant
security:
   basic:
      enabled: true
   sessions: stateless

#postgre
#spring:
#   jpa:
#      generate-ddl: true
#      database: POSTGRESQL
#      show-sql: true
#      hibernate:
#         ddl-auto: update
#         use-new-id-generator-mappings: true
#   datasource:
#      platform: postgres
#      url: jdbc:postgresql://localhost:5432/restaurant
#      username: root
#      password: root
#server:
#   port: 8080
#   contextPath: /restaurant
#security:
#   basic:
#      enabled: true
#   sessions: stateless
